"""Golden parametric bracket `golden_bracket` (CadQuery native editable source).
Generated by AIPD-OS CadQueryBackend (real OpenCASCADE kernel).
Edit PARAMETERS and re-run to regenerate the editable B-Rep model;
set the EXPORT_STEP env var to a path to also write a STEP export.
This file is independently executable and re-loadable.
"""
import cadquery as cq

MODEL_NAME = 'golden_bracket'
PARAMETERS = {
  "chamfer": 2.0,
  "fillet_radius": 3.0,
  "hole_count": 4.0,
  "hole_diameter": 8.0,
  "length": 100.0,
  "thickness": 10.0,
  "width": 50.0
}

def build():
    p = PARAMETERS
    L = float(p['length']); W = float(p['width']); T = float(p['thickness'])
    HD = float(p['hole_diameter']); n = max(1, int(p['hole_count']))
    FR = float(p['fillet_radius']); CH = float(p['chamfer'])
    plate = (cq.Workplane('XY')
             .box(L, W, T)
             .edges('|Z').fillet(FR)
             .faces('>Z').edges().chamfer(CH))
    for i in range(n):
        cx = (L / (n + 1)) * (i + 1) - L / 2
        plate = plate.faces('>Z').workplane().center(cx, 0).hole(HD)
    return plate

if __name__ == '__main__':
    import os
    result = build()
    print('built', result.val().isValid())
    export = os.environ.get('EXPORT_STEP')
    if export:
        from cadquery import exporters
        exporters.export(result, export, exportType='STEP')
