# ruff: noqa: E501
"""product.* 能力登记（手工维护的补充块）。

这 7 项 product.* 能力由 ``scripts/migrate_capability_registry.py`` 在重跑时
合并进 ``src/aipd_os/registry_data.py``（70 项核心 + 7 项 product.*），避免
手写块被覆盖丢失。修改 product.* 能力请改本文件后重跑生成脚本。
"""
from __future__ import annotations

PRODUCT_CAPABILITIES = [
    {"id": "product.derive_insights", "name": "推导洞察候选", "domain": "产品智能", "external_dependency": True, "declaration_file": "docs/architecture/idea_evidence_architecture.md; docs/audit/V5_9_1_RE_AUDIT_MATRIX.md", "implementation_file": "src/aipd_os/tool_adapters/product_adapters.py; src/aipd_os/product_intelligence/provider.py", "entry_point": "aipd_os.tool_adapters.product_adapters.ProductDeriveInsightsAdapter", "run_command": "aipd run（Supervisor S2 product.derive_insights）", "input_output": "ClaimAssessment 上下文 -> Insight 候选（lifecycle=candidate）", "unit_test": "tests/test_product_definition_integrity.py; tests/test_product_intelligence.py", "integration_test": "tests/test_product_intelligence_golden_e2e.py", "e2e_evidence": "Runtime Golden E2E：Supervisor->Router->Adapter->Provider->Service 全链（FakeProvider，tests-only）", "current_limitation": "生产 Provider 未接入；未配置时 discover.available=False -> probe EXTERNAL_DEPENDENCY，execute 写外部任务包（诚实不伪造）"},
    {"id": "product.identify_opportunity", "name": "识别机会候选", "domain": "产品智能", "external_dependency": True, "declaration_file": "docs/architecture/idea_evidence_architecture.md; docs/audit/V5_9_1_RE_AUDIT_MATRIX.md", "implementation_file": "src/aipd_os/tool_adapters/product_adapters.py; src/aipd_os/product_intelligence/provider.py", "entry_point": "aipd_os.tool_adapters.product_adapters.ProductIdentifyOpportunityAdapter", "run_command": "aipd run（Supervisor S2 product.identify_opportunity）", "input_output": "Insights -> Opportunity 候选（不自动 select；selection 是 Owner/Gate 决策，P0-07）", "unit_test": "tests/test_product_definition_integrity.py", "integration_test": "tests/test_product_intelligence_golden_e2e.py", "e2e_evidence": "Runtime Golden E2E", "current_limitation": "生产 Provider 未接入；未配置时诚实 EXTERNAL_DEPENDENCY"},
    {"id": "product.derive_principles", "name": "推导产品原则候选", "domain": "产品智能", "external_dependency": True, "declaration_file": "docs/architecture/idea_evidence_architecture.md; docs/audit/V5_9_1_RE_AUDIT_MATRIX.md", "implementation_file": "src/aipd_os/tool_adapters/product_adapters.py; src/aipd_os/product_intelligence/provider.py", "entry_point": "aipd_os.tool_adapters.product_adapters.ProductDerivePrinciplesAdapter", "run_command": "aipd run（Supervisor S2 product.derive_principles）", "input_output": "Insights + Opportunity -> ProductPrinciple 候选", "unit_test": "tests/test_product_definition_integrity.py", "integration_test": "tests/test_product_intelligence_golden_e2e.py", "e2e_evidence": "Runtime Golden E2E", "current_limitation": "生产 Provider 未接入；未配置时诚实 EXTERNAL_DEPENDENCY"},
    {"id": "product.derive_requirements", "name": "推导需求候选", "domain": "产品智能", "external_dependency": True, "declaration_file": "docs/architecture/idea_evidence_architecture.md; docs/audit/V5_9_1_RE_AUDIT_MATRIX.md", "implementation_file": "src/aipd_os/tool_adapters/product_adapters.py; src/aipd_os/product_intelligence/provider.py", "entry_point": "aipd_os.tool_adapters.product_adapters.ProductDeriveRequirementsAdapter", "run_command": "aipd run（Supervisor S2 product.derive_requirements）", "input_output": "Principles -> Requirement 候选（NPI-ready 字段；candidate 非 approved）", "unit_test": "tests/test_product_definition_integrity.py", "integration_test": "tests/test_product_intelligence_golden_e2e.py", "e2e_evidence": "Runtime Golden E2E", "current_limitation": "生产 Provider 未接入；未配置时诚实 EXTERNAL_DEPENDENCY"},
    {"id": "product.derive_features", "name": "推导功能候选", "domain": "产品智能", "external_dependency": True, "declaration_file": "docs/architecture/idea_evidence_architecture.md; docs/audit/V5_9_1_RE_AUDIT_MATRIX.md", "implementation_file": "src/aipd_os/tool_adapters/product_adapters.py; src/aipd_os/product_intelligence/provider.py", "entry_point": "aipd_os.tool_adapters.product_adapters.ProductDeriveFeaturesAdapter", "run_command": "aipd run（Supervisor S2 product.derive_features）", "input_output": "Requirements -> Feature 候选", "unit_test": "tests/test_product_definition_integrity.py", "integration_test": "tests/test_product_intelligence_golden_e2e.py", "e2e_evidence": "Runtime Golden E2E", "current_limitation": "生产 Provider 未接入；未配置时诚实 EXTERNAL_DEPENDENCY"},
    {"id": "product.create_snapshot", "name": "冻结产品定义快照", "domain": "产品智能", "external_dependency": False, "declaration_file": "docs/audit/V5_9_1_RE_AUDIT_MATRIX.md", "implementation_file": "src/aipd_os/product_intelligence/snapshot.py; src/aipd_os/tool_adapters/product_adapters.py", "entry_point": "aipd_os.tool_adapters.product_adapters.ProductCreateSnapshotAdapter", "run_command": "aipd run（Supervisor S2 product.create_snapshot）", "input_output": "live Product Definition -> immutable Snapshot（id+version refs，content_hash）", "unit_test": "tests/test_product_definition_integrity.py", "integration_test": None, "e2e_evidence": "Runtime Golden E2E；Projection 报告 snapshot fresh/stale", "current_limitation": None},
    {"id": "product.definition_gate", "name": "产品定义门禁", "domain": "产品智能", "external_dependency": False, "declaration_file": "docs/audit/V5_9_1_RE_AUDIT_MATRIX.md", "implementation_file": "src/aipd_os/product_intelligence/gate.py; src/aipd_os/tool_adapters/product_adapters.py", "entry_point": "aipd_os.tool_adapters.product_adapters.ProductDefinitionGateAdapter", "run_command": "aipd product gate --db state.db --project p1", "input_output": "Snapshot -> GateEvaluation（READY/CONDITIONAL/BLOCKED + authorization + eligibility）", "unit_test": "tests/test_product_definition_integrity.py", "integration_test": "tests/test_product_intelligence_golden_e2e.py", "e2e_evidence": "CLI product gate --json；Runtime Golden E2E", "current_limitation": "确定性本地评估（LLM 只可解释不可决定 READY）；生产 Provider 不影响 Gate 可用性"},
]

__all__ = ["PRODUCT_CAPABILITIES"]
